### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by dongdongyee** [walsvid/Generation3D#3]
Thank you for your great work!

Could you add some instructions in README on how to prepare the data we need?

All the best

**Comment by walsvid** [comment]
Hi @dongdongyee , I am very glad that this project is helpful to you. I will update the data preparation process and release the dataset recently.

**Comment by dongdongyee** [comment]
Thanks! looking forward to it :)

**Comment by walsvid** [comment]
> Thanks! looking forward to it :)

As there is a DDL for other conferences recently, I will update the data part as soon as possible, please wait a moment.

**Comment by walsvid** [comment]
Hi @dongdongyee , the data is upload to https://1drv.ms/f/s!Arld9Vmkf6wRgdg8ZcdNvR98vjpSaQ, the explain of data stay tuned.
