### ISSUE TITLE
How can I train for a custom dataset?

### ISSUE THREAD

**Issue by sainatarajan** [walsvid/Generation3D#4]
Hi, thanks for your repo. My dataset consists of images and their corresponding .obj model files. How can I train the model?

**Comment by TumVink** [comment]
With which net would you train?

**Comment by sainatarajan** [comment]
@TumVink Pixel2Mesh and DISN

**Comment by walsvid** [comment]
Hi, @sainatarajan, you can modify the specific dataset class according to your dataset, and the data required for training has been put [here](https://onedrive.live.com/?authkey=%21AMz0pxnqbgueqIE&id=11AC7FA459F55DB9%2127708&cid=11AC7FA459F55DB9).

**Comment by sainatarajan** [comment]
@walsvid Great, thanks! Let me try and get back. Closing this issue for now.

**Comment by sainatarajan** [comment]
Hi @walsvid I don't find the following file: `datasets/data/shapenet/ellipsoid/pixel2mesh_aux_4stages.dat`, can you give me a link to it?
